
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on: []

  frontend:
    working_dir: /app
    image: node:18
    command: sh -c "npm install && npm start"
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
