services:
  - type: web
    name: smartcart-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    buildFilter:
      paths:
        - backend/**/*
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        value: postgresql://personal_projects_db_z83i_user:PWYGhxORg0GWwslhu0gyM6mVkp5tcBDj@dpg-d142m5ogjchc73fnccs0-a/personal_projects_db_z83i


  - type: web
    name: smartcart-frontend
    runtime: node
    plan: free
    rootDir: frontend
    buildCommand: npm run build
    startCommand: serve -s build
    buildFilter:
      paths:
        - frontend/**/*
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://smartcart-backend.onrender.com/api/
