services:
  - type: web
    name: smartcart-backend
    runtime: docker
    region: singapore
    dockerfilePath: ./backend/Dockerfile
    plan: free
    buildFilter:
      paths:
        - backend/**/*
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        value: jdbc:postgresql://dpg-d142m5ogjchc73fnccs0-a:5432/personal_projects_db_z83i
      - key: DATABASE_USER
        value: personal_projects_db_z83i_user
      - key: DATABASE_PASSWORD
        value: PWYGhxORg0GWwslhu0gyM6mVkp5tcBDj


  - type: web
    name: smartcart-frontend
    runtime: node
    region: singapore
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    buildFilter:
      paths:
        - frontend/**/*
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://smartcart-backend-r9l1.onrender.com//api/
